<?php


/**
 * Implements hook_theme().
 */
function custom_block_theme($existing, $type, $theme, $path)
{
    $variables = array(
        'customblock' => array(
            'variables' => array(
                'title_block' => NULL,
                'body_block' => NULL,
                'image_block' => null,
                'position_title' => null
            ),
            'template' => 'customblock',
        ),


    );
    return $variables;
}

